// Function to create and return the HTML string for the navigation bar
const createNavbar = (currentPage) => {
    // Return a template literal containing the full HTML structure for the navbar
    return `
        <div class="navbar">
            <div class="navbar-header">
                <h1 class="logo-title">CREATIVE</h1>
                <p class="logo-subtitle">+ PORTFOLIO</p>
                <h2 class="logo-name">YOUR NAME</h2>
            </div>
            <ul class="navbar-links">
                <li>
                    <a href="index.html" class="${currentPage === 'portfolio' ? 'active' : ''}">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-briefcase"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"></rect><path d="M16 21V5a2 2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"></path></svg>
                        Portfolio
                    </a>
                </li>
                <li>
                    <a href="about.html" class="${currentPage === 'about' ? 'active' : ''}">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                        About Me
                    </a>
                </li>
                <li>
                    <a href="contact.html" class="${currentPage === 'contact' ? 'active' : ''}">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
                        Contact
                    </a>
                </li>
            </ul>
            <div class="navbar-footer">
                <div class="navbar-social-icons">
                    <a href="#"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-linkedin"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg></a>
                </div>
                <p>© 2024 Portfolio</p>
            </div>
        </div>
    `;
};

// Function to load the navbar into the page
const loadNavbar = () => {
    // Get the current page's file name from the URL
    const path = window.location.pathname;
    const page = path.split("/").pop().split(".")[0];
    let currentPage = '';

    // Determine the current page to set the active state on the correct link
    if (page === 'index' || page === '') {
        currentPage = 'portfolio';
    } else if (page === 'about') {
        currentPage = 'about';
    } else if (page === 'contact') {
        currentPage = 'contact';
    }

    // Find the container element where the navbar should be placed
    const navbarContainer = document.getElementById('navbar-container');
    if (navbarContainer) {
        // Set the innerHTML of the container to the HTML generated by createNavbar()
        navbarContainer.innerHTML = createNavbar(currentPage);
    }
};

// Event listener to run the loadNavbar function once the DOM is fully loaded
document.addEventListener('DOMContentLoaded', loadNavbar);